export const DEFAULT_IMAGES = [
  {
    id: '7F65HDP0-E0',
    slug: 'aerial-photography-of-cityscape-near-sea-7F65HDP0-E0',
    alternative_slugs: {
      en: 'aerial-photography-of-cityscape-near-sea-7F65HDP0-E0',
      es: 'fotografia-aerea-de-paisajes-urbanos-cerca-del-mar-7F65HDP0-E0',
      ja: '海近辺の街並みの航空写真-7F65HDP0-E0',
      fr: 'photographie-aerienne-dun-paysage-urbain-pres-de-la-mer-7F65HDP0-E0',
      it: 'fotografia-aerea-del-paesaggio-urbano-vicino-al-mare-7F65HDP0-E0',
      ko: '바다-근처-도시-풍경의-항공-사진-7F65HDP0-E0',
      de: 'luftaufnahmen-des-stadtbildes-in-meeresnahe-7F65HDP0-E0',
      pt: 'fotografia-aerea-da-paisagem-urbana-perto-do-mar-7F65HDP0-E0',
    },
    created_at: '2017-01-06T19:07:43Z',
    updated_at: '2025-04-11T07:28:29Z',
    promoted_at: '2017-01-06T19:07:43Z',
    width: 6000,
    height: 4000,
    color: '#f3f3f3',
    blur_hash: 'L,LzpqX8jZax~VjYj[kC%MaxWBof',
    description: 'Wildest sunset ever',
    alt_description: 'aerial photography of cityscape near sea',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDQzNzI1MDJ8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDQzNzI1MDJ8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDQzNzI1MDJ8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDQzNzI1MDJ8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDQzNzI1MDJ8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1483729558449-99ef09a8c325',
    },
    links: {
      self: 'https://api.unsplash.com/photos/aerial-photography-of-cityscape-near-sea-7F65HDP0-E0',
      html: 'https://unsplash.com/photos/aerial-photography-of-cityscape-near-sea-7F65HDP0-E0',
      download:
        'https://unsplash.com/photos/7F65HDP0-E0/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDQzNzI1MDJ8',
      download_location:
        'https://api.unsplash.com/photos/7F65HDP0-E0/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDQzNzI1MDJ8',
    },
    likes: 3041,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      wallpapers: {
        status: 'approved',
        approved_on: '2020-04-06T14:20:09Z',
      },
    },
    asset_type: 'photo',
    user: {
      id: '2xVXrJvhhy0',
      updated_at: '2025-04-02T19:53:28Z',
      username: 'agustindiazg',
      name: 'Agustin Diaz Gargiulo',
      first_name: 'Agustin',
      last_name: 'Diaz Gargiulo',
      twitter_username: 'agussdiaz28',
      portfolio_url: 'https://www.eyeem.com/u/mariandiaz___',
      bio: 'Developer | Photographer',
      location: 'Tandil, Argentina',
      links: {
        self: 'https://api.unsplash.com/users/agustindiazg',
        html: 'https://unsplash.com/@agustindiazg',
        photos: 'https://api.unsplash.com/users/agustindiazg/photos',
        likes: 'https://api.unsplash.com/users/agustindiazg/likes',
        portfolio: 'https://api.unsplash.com/users/agustindiazg/portfolio',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1632878091545-0896749d4eaeimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1632878091545-0896749d4eaeimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1632878091545-0896749d4eaeimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'agussdiaz28',
      total_collections: 0,
      total_likes: 461,
      total_photos: 11,
      total_promoted_photos: 4,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'agussdiaz28',
        portfolio_url: 'https://www.eyeem.com/u/mariandiaz___',
        twitter_username: 'agussdiaz28',
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: 'Rio de Janeiro, Brazil',
      city: 'Rio de Janeiro',
      country: 'Brazil',
      position: {
        latitude: -22.9068467,
        longitude: -43.1728965,
      },
    },
    views: 50467100,
    downloads: 337995,
  },
  {
    id: '16CbnBFveF0',
    slug: 'green-palm-plant-in-close-up-photography-16CbnBFveF0',
    alternative_slugs: {
      en: 'green-palm-plant-in-close-up-photography-16CbnBFveF0',
      es: 'planta-de-palma-verde-en-fotografia-de-primer-plano-16CbnBFveF0',
      ja: 'クローズアップ写真の緑のヤシの木-16CbnBFveF0',
      fr: 'plante-de-palmier-vert-en-photographie-en-gros-plan-16CbnBFveF0',
      it: 'pianta-di-palma-verde-in-fotografia-ravvicinata-16CbnBFveF0',
      ko: '클로즈업-사진의-녹색-야자-식물-16CbnBFveF0',
      de: 'grune-palmenpflanze-in-nahaufnahme-16CbnBFveF0',
      pt: 'planta-de-palmeira-verde-na-fotografia-de-perto-16CbnBFveF0',
    },
    created_at: '2020-03-23T20:25:52Z',
    updated_at: '2025-02-23T09:35:47Z',
    promoted_at: '2020-03-24T14:03:01Z',
    width: 6000,
    height: 4000,
    color: '#c0d9c0',
    blur_hash: 'LVKoAF.7_3Mx~qWEIVkVD*t8M{%M',
    description: null,
    alt_description: 'green palm plant in close up photography',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1584995123985-061faeadde2f?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1584995123985-061faeadde2f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1584995123985-061faeadde2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1584995123985-061faeadde2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1584995123985-061faeadde2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1584995123985-061faeadde2f',
    },
    links: {
      self: 'https://api.unsplash.com/photos/green-palm-plant-in-close-up-photography-16CbnBFveF0',
      html: 'https://unsplash.com/photos/green-palm-plant-in-close-up-photography-16CbnBFveF0',
      download:
        'https://unsplash.com/photos/16CbnBFveF0/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/16CbnBFveF0/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 129,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: '744ZqQJzG8U',
      updated_at: '2024-10-10T21:26:21Z',
      username: 'martinpechy',
      name: 'Martin Péchy',
      first_name: 'Martin',
      last_name: 'Péchy',
      twitter_username: null,
      portfolio_url: null,
      bio: 'Passionate about design and architecture. Designer/Filmmaker.',
      location: 'Slovakia',
      links: {
        self: 'https://api.unsplash.com/users/martinpechy',
        html: 'https://unsplash.com/@martinpechy',
        photos: 'https://api.unsplash.com/users/martinpechy/photos',
        likes: 'https://api.unsplash.com/users/martinpechy/likes',
        portfolio: 'https://api.unsplash.com/users/martinpechy/portfolio',
        following: 'https://api.unsplash.com/users/martinpechy/following',
        followers: 'https://api.unsplash.com/users/martinpechy/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1543487248792-8147dba3aad4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1543487248792-8147dba3aad4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1543487248792-8147dba3aad4?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'martinpechy',
      total_collections: 0,
      total_likes: 0,
      total_photos: 81,
      total_promoted_photos: 38,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: 'martinpechy',
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'SONY',
      model: 'ILCE-7M2',
      name: 'SONY, ILCE-7M2',
      exposure_time: '1/640',
      aperture: '3.5',
      focal_length: '28.0',
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 10898279,
    downloads: 14102,
  },
  {
    id: 'qe_EJGKxwQ0',
    slug: 'an-aerial-view-of-a-road-in-the-middle-of-a-forest-qe_EJGKxwQ0',
    alternative_slugs: {
      en: 'an-aerial-view-of-a-road-in-the-middle-of-a-forest-qe_EJGKxwQ0',
      es: 'una-vista-aerea-de-una-carretera-en-medio-de-un-bosque-qe_EJGKxwQ0',
      ja: '森の真ん中にある道路の空中写真-qe_EJGKxwQ0',
      fr: 'vue-aerienne-dune-route-au-milieu-dune-foret-qe_EJGKxwQ0',
      it: 'una-veduta-aerea-di-una-strada-nel-mezzo-di-una-foresta-qe_EJGKxwQ0',
      ko: '숲-한가운데에-있는-도로의-조감도-qe_EJGKxwQ0',
      de: 'luftaufnahme-einer-strasse-mitten-im-wald-qe_EJGKxwQ0',
      pt: 'vista-aerea-de-uma-estrada-no-meio-de-uma-floresta-qe_EJGKxwQ0',
    },
    created_at: '2023-08-20T20:16:04Z',
    updated_at: '2025-02-23T13:52:41Z',
    promoted_at: '2023-08-25T07:40:01Z',
    width: 4000,
    height: 2250,
    color: '#c0a68c',
    blur_hash: 'LNG@_C4:0L?GRk-VRkfhNHjtofjZ',
    description: null,
    alt_description: 'an aerial view of a road in the middle of a forest',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1692562557018-376bfa995d95?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1692562557018-376bfa995d95?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1692562557018-376bfa995d95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1692562557018-376bfa995d95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1692562557018-376bfa995d95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1692562557018-376bfa995d95',
    },
    links: {
      self: 'https://api.unsplash.com/photos/an-aerial-view-of-a-road-in-the-middle-of-a-forest-qe_EJGKxwQ0',
      html: 'https://unsplash.com/photos/an-aerial-view-of-a-road-in-the-middle-of-a-forest-qe_EJGKxwQ0',
      download:
        'https://unsplash.com/photos/qe_EJGKxwQ0/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/qe_EJGKxwQ0/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 38,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'eP7J510Osfs',
      updated_at: '2025-02-23T07:34:22Z',
      username: 'razvan_trif',
      name: 'Razvan Trif',
      first_name: 'Razvan',
      last_name: 'Trif',
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: null,
      links: {
        self: 'https://api.unsplash.com/users/razvan_trif',
        html: 'https://unsplash.com/@razvan_trif',
        photos: 'https://api.unsplash.com/users/razvan_trif/photos',
        likes: 'https://api.unsplash.com/users/razvan_trif/likes',
        portfolio: 'https://api.unsplash.com/users/razvan_trif/portfolio',
        following: 'https://api.unsplash.com/users/razvan_trif/following',
        followers: 'https://api.unsplash.com/users/razvan_trif/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1707569361981-9ea15908241bimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1707569361981-9ea15908241bimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1707569361981-9ea15908241bimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 25,
      total_photos: 72,
      total_promoted_photos: 1,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: 0,
        longitude: 0,
      },
    },
    views: 9725714,
    downloads: 81217,
  },
  {
    id: 'G6ntxf-QoSI',
    slug: 'grey-spiral-stairs-G6ntxf-QoSI',
    alternative_slugs: {
      en: 'grey-spiral-stairs-G6ntxf-QoSI',
      es: 'escaleras-de-caracol-grises-G6ntxf-QoSI',
      ja: '灰色の螺旋階段-G6ntxf-QoSI',
      fr: 'escaliers-en-colimacon-gris-G6ntxf-QoSI',
      it: 'scale-a-chiocciola-grigie-G6ntxf-QoSI',
      ko: '회색-나선형-계단-G6ntxf-QoSI',
      de: 'graue-wendeltreppe-G6ntxf-QoSI',
      pt: 'escadas-espirais-cinzentas-G6ntxf-QoSI',
    },
    created_at: '2019-05-22T20:23:19Z',
    updated_at: '2025-02-23T09:21:20Z',
    promoted_at: '2019-05-23T06:49:04Z',
    width: 7952,
    height: 5304,
    color: '#262626',
    blur_hash: 'LOBDc#X901xuM|jZt6WC8_j[-;Ri',
    description: null,
    alt_description: 'grey spiral stairs',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1558556515-2c1a28062c9d?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1558556515-2c1a28062c9d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1558556515-2c1a28062c9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1558556515-2c1a28062c9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1558556515-2c1a28062c9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1558556515-2c1a28062c9d',
    },
    links: {
      self: 'https://api.unsplash.com/photos/grey-spiral-stairs-G6ntxf-QoSI',
      html: 'https://unsplash.com/photos/grey-spiral-stairs-G6ntxf-QoSI',
      download:
        'https://unsplash.com/photos/G6ntxf-QoSI/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/G6ntxf-QoSI/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 299,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'nFtx7xLaipM',
      updated_at: '2025-01-27T18:33:55Z',
      username: 'osmanrana',
      name: 'Osman Rana',
      first_name: 'Osman',
      last_name: 'Rana',
      twitter_username: null,
      portfolio_url: 'Https://www.oranaphotography.com',
      bio: null,
      location: 'Boston, USA',
      links: {
        self: 'https://api.unsplash.com/users/osmanrana',
        html: 'https://unsplash.com/@osmanrana',
        photos: 'https://api.unsplash.com/users/osmanrana/photos',
        likes: 'https://api.unsplash.com/users/osmanrana/likes',
        portfolio: 'https://api.unsplash.com/users/osmanrana/portfolio',
        following: 'https://api.unsplash.com/users/osmanrana/following',
        followers: 'https://api.unsplash.com/users/osmanrana/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1470101925356-0e31654f5fad?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1470101925356-0e31654f5fad?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1470101925356-0e31654f5fad?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'ranagraphs',
      total_collections: 0,
      total_likes: 580,
      total_photos: 280,
      total_promoted_photos: 131,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'ranagraphs',
        portfolio_url: 'Https://www.oranaphotography.com',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'SONY',
      model: 'ILCE-7RM3',
      name: 'SONY, ILCE-7RM3',
      exposure_time: '1/1000',
      aperture: '1.4',
      focal_length: '85.0',
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 14145864,
    downloads: 12549,
  },
  {
    id: 'WPDbYdFOtbw',
    slug: 'a-group-of-mountains-with-snow-on-them-WPDbYdFOtbw',
    alternative_slugs: {
      en: 'a-group-of-mountains-with-snow-on-them-WPDbYdFOtbw',
      es: 'un-grupo-de-montanas-con-nieve-WPDbYdFOtbw',
      ja: '雪が積もった山々群-WPDbYdFOtbw',
      fr: 'un-groupe-de-montagnes-avec-de-la-neige-dessus-WPDbYdFOtbw',
      it: 'un-gruppo-di-montagne-con-la-neve-sopra-WPDbYdFOtbw',
      ko: '눈이-쌓인-산의-무리-WPDbYdFOtbw',
      de: 'eine-gruppe-von-bergen-mit-schnee-auf-ihnen-WPDbYdFOtbw',
      pt: 'um-grupo-de-montanhas-com-neve-sobre-eles-WPDbYdFOtbw',
    },
    created_at: '2024-10-21T02:07:47Z',
    updated_at: '2025-02-23T11:24:17Z',
    promoted_at: '2024-10-23T07:14:15Z',
    width: 7008,
    height: 4672,
    color: '#c0c0c0',
    blur_hash: 'LPHV9zs.NIWB-=%Lxaof0KRjads:',
    description: null,
    alt_description: 'A group of mountains with snow on them',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1729476266027-a687e42116ce?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1729476266027-a687e42116ce?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1729476266027-a687e42116ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1729476266027-a687e42116ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1729476266027-a687e42116ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1729476266027-a687e42116ce',
    },
    links: {
      self: 'https://api.unsplash.com/photos/a-group-of-mountains-with-snow-on-them-WPDbYdFOtbw',
      html: 'https://unsplash.com/photos/a-group-of-mountains-with-snow-on-them-WPDbYdFOtbw',
      download:
        'https://unsplash.com/photos/WPDbYdFOtbw/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/WPDbYdFOtbw/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 54,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: 'approved',
        approved_on: '2024-10-21T06:27:36Z',
      },
    },
    asset_type: 'photo',
    user: {
      id: 'g8RmniQWB8E',
      updated_at: '2025-02-23T04:33:56Z',
      username: 'ventiviews',
      name: 'Venti Views',
      first_name: 'Venti',
      last_name: 'Views',
      twitter_username: null,
      portfolio_url: 'http://ventiviews.com',
      bio: "Amazing content for amazing people. \r\nCameras of choice are Sony A7 IV, Mavic 3, iPhone 15 pro AND Nikon f100 because who doesn't love film.",
      location: 'Los Angeles',
      links: {
        self: 'https://api.unsplash.com/users/ventiviews',
        html: 'https://unsplash.com/@ventiviews',
        photos: 'https://api.unsplash.com/users/ventiviews/photos',
        likes: 'https://api.unsplash.com/users/ventiviews/likes',
        portfolio: 'https://api.unsplash.com/users/ventiviews/portfolio',
        following: 'https://api.unsplash.com/users/ventiviews/following',
        followers: 'https://api.unsplash.com/users/ventiviews/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1670385206797-ac15dbb4a5caimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1670385206797-ac15dbb4a5caimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1670385206797-ac15dbb4a5caimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'ventiviews',
      total_collections: 16,
      total_likes: 264,
      total_photos: 857,
      total_promoted_photos: 312,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: 'ventiviews',
        portfolio_url: 'http://ventiviews.com',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'SONY',
      model: 'ILCE-7M4',
      name: 'SONY, ILCE-7M4',
      exposure_time: '1/2000',
      aperture: '5.0',
      focal_length: '113.0',
      iso: 250,
    },
    location: {
      name: 'Fitz Roy, Santa Cruz, Santa Cruz Province, Argentina',
      city: 'Fitz Roy',
      country: 'Argentina',
      position: {
        latitude: -47.02592,
        longitude: -67.247959,
      },
    },
    views: 2966711,
    downloads: 15759,
  },
  {
    id: '715v3NOlVhU',
    slug: 'top-angle-view-of-green-sea-waves-715v3NOlVhU',
    alternative_slugs: {
      en: 'top-angle-view-of-green-sea-waves-715v3NOlVhU',
      es: 'vista-del-angulo-superior-de-las-olas-verdes-del-mar-715v3NOlVhU',
      ja: '緑の海の波の上角ビュー-715v3NOlVhU',
      fr: 'vue-de-langle-superieur-des-vagues-vertes-de-la-mer-715v3NOlVhU',
      it: 'vista-angolare-dallalto-delle-onde-verdi-del-mare-715v3NOlVhU',
      ko: '녹색-바다-파도의-상단-각도보기-715v3NOlVhU',
      de: 'top-angle-ansicht-der-grunen-meereswellen-715v3NOlVhU',
      pt: 'vista-angular-superior-das-ondas-verdes-do-mar-715v3NOlVhU',
    },
    created_at: '2019-08-05T13:23:51Z',
    updated_at: '2025-02-23T12:24:44Z',
    promoted_at: '2019-08-06T15:30:11Z',
    width: 2815,
    height: 3722,
    color: '#262626',
    blur_hash: 'LXC%pmni%MRP*0t7xujFx]tRa{oz',
    description:
      'Drone shot of ocean crashing against rocks. Margaret River Region, Western Australia',
    alt_description: 'top angle view of green sea waves',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1565010505532-3b09aa5f2543?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1565010505532-3b09aa5f2543?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1565010505532-3b09aa5f2543?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1565010505532-3b09aa5f2543?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1565010505532-3b09aa5f2543?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1565010505532-3b09aa5f2543',
    },
    links: {
      self: 'https://api.unsplash.com/photos/top-angle-view-of-green-sea-waves-715v3NOlVhU',
      html: 'https://unsplash.com/photos/top-angle-view-of-green-sea-waves-715v3NOlVhU',
      download:
        'https://unsplash.com/photos/715v3NOlVhU/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/715v3NOlVhU/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 213,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'XaQmwtinZfk',
      updated_at: '2024-10-31T18:26:15Z',
      username: 'trism',
      name: 'Tristan McKenzie',
      first_name: 'Tristan',
      last_name: 'McKenzie',
      twitter_username: null,
      portfolio_url: 'https://www.instagram.com/t.r.i.s.m/',
      bio: 'International Freelance Photographer - Head on over to @t.r.i.s.m to see my day to day! >>>\r\nFor all commercial enquiries send me an email at trismckenziephoto@gmail.com',
      location: 'Perth, Australia',
      links: {
        self: 'https://api.unsplash.com/users/trism',
        html: 'https://unsplash.com/@trism',
        photos: 'https://api.unsplash.com/users/trism/photos',
        likes: 'https://api.unsplash.com/users/trism/likes',
        portfolio: 'https://api.unsplash.com/users/trism/portfolio',
        following: 'https://api.unsplash.com/users/trism/following',
        followers: 'https://api.unsplash.com/users/trism/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1565007372445-16a9852b0e1d?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1565007372445-16a9852b0e1d?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1565007372445-16a9852b0e1d?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 't.r.i.s.m',
      total_collections: 0,
      total_likes: 0,
      total_photos: 13,
      total_promoted_photos: 6,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: 't.r.i.s.m',
        portfolio_url: 'https://www.instagram.com/t.r.i.s.m/',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 17397796,
    downloads: 9966,
  },
  {
    id: 'pbuuVSR80Kc',
    slug: 'a-mountain-range-with-a-few-rocks-in-the-foreground-pbuuVSR80Kc',
    alternative_slugs: {
      en: 'a-mountain-range-with-a-few-rocks-in-the-foreground-pbuuVSR80Kc',
      es: 'una-cadena-montanosa-con-algunas-rocas-en-primer-plano-pbuuVSR80Kc',
      ja: '前景にいくつかの岩がある山脈-pbuuVSR80Kc',
      fr: 'une-chaine-de-montagnes-avec-quelques-rochers-au-premier-plan-pbuuVSR80Kc',
      it: 'una-catena-montuosa-con-alcune-rocce-in-primo-piano-pbuuVSR80Kc',
      ko: '전경에-몇-개의-바위가-있는-산맥-pbuuVSR80Kc',
      de: 'eine-bergkette-mit-ein-paar-felsen-im-vordergrund-pbuuVSR80Kc',
      pt: 'uma-cordilheira-com-algumas-rochas-em-primeiro-plano-pbuuVSR80Kc',
    },
    created_at: '2023-08-31T05:28:01Z',
    updated_at: '2025-02-23T13:53:17Z',
    promoted_at: '2023-09-02T13:48:01Z',
    width: 3117,
    height: 4675,
    color: '#c0c0a6',
    blur_hash: 'LiGuO8R*kCj[~pjsa}j[OFoee.az',
    description: 'Alabama Hills, CA',
    alt_description: 'a mountain range with a few rocks in the foreground',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1693459679879-0aec769723c7?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1693459679879-0aec769723c7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1693459679879-0aec769723c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1693459679879-0aec769723c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1693459679879-0aec769723c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1693459679879-0aec769723c7',
    },
    links: {
      self: 'https://api.unsplash.com/photos/a-mountain-range-with-a-few-rocks-in-the-foreground-pbuuVSR80Kc',
      html: 'https://unsplash.com/photos/a-mountain-range-with-a-few-rocks-in-the-foreground-pbuuVSR80Kc',
      download:
        'https://unsplash.com/photos/pbuuVSR80Kc/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/pbuuVSR80Kc/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 119,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: '3_4Fk2MhZ94',
      updated_at: '2024-12-18T01:17:18Z',
      username: 'patslens',
      name: 'Pat Rindone',
      first_name: 'Pat',
      last_name: 'Rindone',
      twitter_username: null,
      portfolio_url: null,
      bio: 'Wedding, Landscape, Commercial, and Freelance photographer.',
      location: 'Just a wedding photographer taking pictures in neature.',
      links: {
        self: 'https://api.unsplash.com/users/patslens',
        html: 'https://unsplash.com/@patslens',
        photos: 'https://api.unsplash.com/users/patslens/photos',
        likes: 'https://api.unsplash.com/users/patslens/likes',
        portfolio: 'https://api.unsplash.com/users/patslens/portfolio',
        following: 'https://api.unsplash.com/users/patslens/following',
        followers: 'https://api.unsplash.com/users/patslens/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1565626638027-1b1dd96a9293?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1565626638027-1b1dd96a9293?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1565626638027-1b1dd96a9293?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'patslens',
      total_collections: 0,
      total_likes: 12,
      total_photos: 16,
      total_promoted_photos: 12,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: 'patslens',
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'Canon',
      model: '6D',
      name: 'Canon, 6D',
      exposure_time: '1/640',
      aperture: '5.6',
      focal_length: '70.0',
      iso: 100,
    },
    location: {
      name: 'Alabama Hills, Independence, United States',
      city: 'Independence',
      country: 'United States',
      position: {
        latitude: 36.60263337668222,
        longitude: -118.1145348958003,
      },
    },
    views: 2574314,
    downloads: 25806,
  },
  {
    id: 'pMImt780DDM',
    slug: 'yellow-and-green-petaled-flower-in-white-vase-pMImt780DDM',
    alternative_slugs: {
      en: 'yellow-and-green-petaled-flower-in-white-vase-pMImt780DDM',
      es: 'flor-de-petalos-amarillos-y-verdes-en-jarron-blanco-pMImt780DDM',
      ja: '白い花瓶に黄色と緑の花びらの花-pMImt780DDM',
      fr: 'fleur-a-petales-jaunes-et-verts-dans-un-vase-blanc-pMImt780DDM',
      it: 'fiore-petalo-giallo-e-verde-in-vaso-bianco-pMImt780DDM',
      ko: '흰색-꽃병에-노란색과-녹색-꽃잎-꽃-pMImt780DDM',
      de: 'gelbe-und-grun-blattrige-blume-in-weisser-vase-pMImt780DDM',
      pt: 'flor-de-petala-amarela-e-verde-no-vaso-branco-pMImt780DDM',
    },
    created_at: '2018-10-09T11:20:00Z',
    updated_at: '2025-02-23T09:12:53Z',
    promoted_at: '2018-10-09T16:16:26Z',
    width: 4000,
    height: 6000,
    color: '#c0c0d9',
    blur_hash: 'LIKeTRIoIVob%%WAe-WY8^j[oeof',
    description: 'flower',
    alt_description: 'yellow and green petaled flower in white vase',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1539083943273-138a8ba5486d?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1539083943273-138a8ba5486d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1539083943273-138a8ba5486d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1539083943273-138a8ba5486d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1539083943273-138a8ba5486d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1539083943273-138a8ba5486d',
    },
    links: {
      self: 'https://api.unsplash.com/photos/yellow-and-green-petaled-flower-in-white-vase-pMImt780DDM',
      html: 'https://unsplash.com/photos/yellow-and-green-petaled-flower-in-white-vase-pMImt780DDM',
      download:
        'https://unsplash.com/photos/pMImt780DDM/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/pMImt780DDM/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 246,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'ooF-5CcxHZ8',
      updated_at: '2025-02-19T07:18:51Z',
      username: 'hayakasa',
      name: 'Ryoji Hayasaka',
      first_name: 'Ryoji',
      last_name: 'Hayasaka',
      twitter_username: 'r_hayakasa',
      portfolio_url: 'https://hyks.jp',
      bio: 'living in japan as a programmer, or a photographer.',
      location: 'okayama, japan',
      links: {
        self: 'https://api.unsplash.com/users/hayakasa',
        html: 'https://unsplash.com/@hayakasa',
        photos: 'https://api.unsplash.com/users/hayakasa/photos',
        likes: 'https://api.unsplash.com/users/hayakasa/likes',
        portfolio: 'https://api.unsplash.com/users/hayakasa/portfolio',
        following: 'https://api.unsplash.com/users/hayakasa/following',
        followers: 'https://api.unsplash.com/users/hayakasa/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1482830527774-c70a73c9c0a0?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1482830527774-c70a73c9c0a0?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1482830527774-c70a73c9c0a0?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'hayakasa',
      total_collections: 5,
      total_likes: 37,
      total_photos: 147,
      total_promoted_photos: 14,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: 'hayakasa',
        portfolio_url: 'https://hyks.jp',
        twitter_username: 'r_hayakasa',
        paypal_email: null,
      },
    },
    exif: {
      make: 'SONY',
      model: 'ILCE-7M2',
      name: 'SONY, ILCE-7M2',
      exposure_time: '1/100',
      aperture: '1.8',
      focal_length: '55.0',
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 22764304,
    downloads: 11841,
  },
  {
    id: 'XIhGAhtdKns',
    slug: 'rock-formation-on-body-of-water-XIhGAhtdKns',
    alternative_slugs: {
      en: 'rock-formation-on-body-of-water-XIhGAhtdKns',
      es: 'formacion-rocosa-en-el-cuerpo-de-agua-XIhGAhtdKns',
      ja: '水域の岩石層-XIhGAhtdKns',
      fr: 'formation-rocheuse-sur-plan-deau-XIhGAhtdKns',
      it: 'formazione-rocciosa-sullo-specchio-dacqua-XIhGAhtdKns',
      ko: '수역의-암석-XIhGAhtdKns',
      de: 'gesteinsformation-auf-gewasser-XIhGAhtdKns',
      pt: 'formacao-rochosa-no-corpo-dagua-XIhGAhtdKns',
    },
    created_at: '2018-12-01T21:15:46Z',
    updated_at: '2025-02-23T12:14:12Z',
    promoted_at: '2018-12-03T06:36:31Z',
    width: 5760,
    height: 3600,
    color: '#73738c',
    blur_hash: 'LrHA^taxj[WB}Uayayj[-7ayjZj]',
    description: 'Before You Leave',
    alt_description: 'rock formation on body of water',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1543698910-a6e22f900282?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1543698910-a6e22f900282?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1543698910-a6e22f900282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1543698910-a6e22f900282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1543698910-a6e22f900282?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1543698910-a6e22f900282',
    },
    links: {
      self: 'https://api.unsplash.com/photos/rock-formation-on-body-of-water-XIhGAhtdKns',
      html: 'https://unsplash.com/photos/rock-formation-on-body-of-water-XIhGAhtdKns',
      download:
        'https://unsplash.com/photos/XIhGAhtdKns/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/XIhGAhtdKns/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 115,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: 'approved',
        approved_on: '2020-04-06T14:20:12Z',
      },
    },
    asset_type: 'photo',
    user: {
      id: 'uMJXuywXLiU',
      updated_at: '2025-02-20T15:49:19Z',
      username: 'iamthedave',
      name: 'Dave Hoefler',
      first_name: 'Dave',
      last_name: 'Hoefler',
      twitter_username: null,
      portfolio_url: 'https://www.davehoefler.com/',
      bio: 'I like nature.',
      location: null,
      links: {
        self: 'https://api.unsplash.com/users/iamthedave',
        html: 'https://unsplash.com/@iamthedave',
        photos: 'https://api.unsplash.com/users/iamthedave/photos',
        likes: 'https://api.unsplash.com/users/iamthedave/likes',
        portfolio: 'https://api.unsplash.com/users/iamthedave/portfolio',
        following: 'https://api.unsplash.com/users/iamthedave/following',
        followers: 'https://api.unsplash.com/users/iamthedave/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1728755589926-78ac077e87a6image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1728755589926-78ac077e87a6image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1728755589926-78ac077e87a6image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: null,
      total_collections: 0,
      total_likes: 176,
      total_photos: 1010,
      total_promoted_photos: 433,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: null,
        portfolio_url: 'https://www.davehoefler.com/',
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: 'Canon',
      model: 'Canon EOS 5D Mark III',
      name: 'Canon, EOS 5D Mark III',
      exposure_time: '5',
      aperture: '16.0',
      focal_length: '220.0',
      iso: 100,
    },
    location: {
      name: 'Bandon, US',
      city: 'Bandon',
      country: 'US',
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 8589282,
    downloads: 7492,
  },
  {
    id: 'Ipc6X2UvJeI',
    slug: 'selective-focus-photography-of-green-leaf-plant-Ipc6X2UvJeI',
    alternative_slugs: {
      en: 'selective-focus-photography-of-green-leaf-plant-Ipc6X2UvJeI',
      es: 'fotografia-de-enfoque-selectivo-de-planta-de-hoja-verde-Ipc6X2UvJeI',
      ja: '緑の葉植物のセレクティブフォーカス写真-Ipc6X2UvJeI',
      fr: 'photographie-selective-de-la-plante-a-feuilles-vertes-Ipc6X2UvJeI',
      it: 'fotografia-a-fuoco-selettiva-di-una-pianta-a-foglia-verde-Ipc6X2UvJeI',
      ko: '녹색-잎-식물의-선택적-초점-사진-Ipc6X2UvJeI',
      de: 'selektive-fokusfotografie-von-grunen-blattpflanzen-Ipc6X2UvJeI',
      pt: 'fotografia-com-foco-seletivo-de-planta-de-folha-verde-Ipc6X2UvJeI',
    },
    created_at: '2017-04-04T13:23:48Z',
    updated_at: '2025-02-23T09:04:10Z',
    promoted_at: '2017-04-04T16:07:09Z',
    width: 6000,
    height: 4000,
    color: '#0c2626',
    blur_hash: 'LD97qU?Y030MR8n+xtRk9aRk-.-o',
    description: null,
    alt_description: 'selective focus photography of green leaf plant',
    breadcrumbs: [],
    urls: {
      raw: 'https://images.unsplash.com/photo-1491312207232-9856fad8f440?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3',
      full: 'https://images.unsplash.com/photo-1491312207232-9856fad8f440?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=85',
      regular:
        'https://images.unsplash.com/photo-1491312207232-9856fad8f440?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=1080',
      small:
        'https://images.unsplash.com/photo-1491312207232-9856fad8f440?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=400',
      thumb:
        'https://images.unsplash.com/photo-1491312207232-9856fad8f440?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8&ixlib=rb-4.0.3&q=80&w=200',
      small_s3:
        'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1491312207232-9856fad8f440',
    },
    links: {
      self: 'https://api.unsplash.com/photos/selective-focus-photography-of-green-leaf-plant-Ipc6X2UvJeI',
      html: 'https://unsplash.com/photos/selective-focus-photography-of-green-leaf-plant-Ipc6X2UvJeI',
      download:
        'https://unsplash.com/photos/Ipc6X2UvJeI/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
      download_location:
        'https://api.unsplash.com/photos/Ipc6X2UvJeI/download?ixid=M3w3MTM1NzR8MHwxfHJhbmRvbXx8fHx8fHx8fDE3NDAzMjE1ODR8',
    },
    likes: 259,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: 'photo',
    user: {
      id: 'QiFlI7IL89s',
      updated_at: '2024-12-18T04:01:01Z',
      username: 'daniel840528',
      name: 'Daniel Tseng',
      first_name: 'Daniel',
      last_name: 'Tseng',
      twitter_username: null,
      portfolio_url: null,
      bio: 'Photographer form Taiwan 🇹🇼',
      location: null,
      links: {
        self: 'https://api.unsplash.com/users/daniel840528',
        html: 'https://unsplash.com/@daniel840528',
        photos: 'https://api.unsplash.com/users/daniel840528/photos',
        likes: 'https://api.unsplash.com/users/daniel840528/likes',
        portfolio: 'https://api.unsplash.com/users/daniel840528/portfolio',
        following: 'https://api.unsplash.com/users/daniel840528/following',
        followers: 'https://api.unsplash.com/users/daniel840528/followers',
      },
      profile_image: {
        small:
          'https://images.unsplash.com/profile-1518841903078-2fe806ad7862?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
        medium:
          'https://images.unsplash.com/profile-1518841903078-2fe806ad7862?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
        large:
          'https://images.unsplash.com/profile-1518841903078-2fe806ad7862?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      },
      instagram_username: 'danpeaks',
      total_collections: 1,
      total_likes: 263,
      total_photos: 96,
      total_promoted_photos: 17,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: 'danpeaks',
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: null,
      model: null,
      name: null,
      exposure_time: null,
      aperture: null,
      focal_length: null,
      iso: null,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 9559645,
    downloads: 9433,
  },
];
